### ISSUE TITLE
Any way to play test with headed (gui) browser?

### ISSUE THREAD

**Issue by ivan-borisov** [ryanc414/pytest_runner#15]
For example i want to pass custom arguments to pytest, because i use some pytest plugins for reports and browsers

**Comment by ryanc414** [comment]
Hi Ivan, so there's a couple points to address here.

With regards to the browser, it will open in whatever your system default browser is set to. However, if you want to open in a different browser, you can pass --no-browse flag to pytest_commander and instead manually navigate to http://localhost:5000/ in your browser of choice after it has started. As a future enhancement I could potentially add the option to pass the name of a browser executable as a command-line parameter.

Regarding passing custom args to pytest, this is possibly a little more tricky since pytest_commander does not invoke the `pytest` CLI command but instead calls the `pytest.main()` library function. It should be possible to pass extra args to this method but there might be some limitations, I would have to look into it further.

**Comment by ryanc414** [comment]
Hey - if you update to the latest release you should see a new `--browser` option (or -b for short), this allows you to pass in the name of a browser executable to use in preference to your system's default browser. This can either be the full absolute path or just the command name if it can be found on your PATH.

With regards to your question about extra pytest plugins, you may customise the options passed to pytest by creating a pytest.ini file as described in the official docs: https://docs.pytest.org/en/latest/reference/customize.html#pytest-ini

Let me know if you have any further questions or issues, I'll close this for now.
