### ISSUE TITLE
GUI can't handle multiprocess tests

### ISSUE THREAD

**Issue by v-polonskyi** [ryanc414/pytest_runner#16]
I'm using https://pypi.org/project/pytest-xdist/ to run my test in parallel (test runs in different processes by using '-n auto' option)
- GUI can't track execution status
- GUI broke order of test executing ('--dist loadscope' option)

**Comment by ryanc414** [comment]
Hi, thanks for trying out the project. Can I ask how exactly you are combining pytest-xdist with pytest-commander? Currently there is no documented/supported way to use additional pytest plugins when running tests with pytest-commander.

I have been thinking recently about how I might support the use of additional plugins. However, plugins like xdist which run the tests over multiple processes will likely never be supported. This is because the process running the tests needs to communicate with the process running the pytest-commander server to update test status - it's not clear how that would work when there are multiple processes spawned to run tests which aren't under the control of pytest-commander.

As well as the technical difficulties noted above, it's not clear to me that there is a real need to support integration of xdist multiprocessing with pytest-commander. You can already run tests in multiple processes by clicking on multiple tests in the UI, each test or test group clicked will run in a separate process.

**Comment by v-polonskyi** [comment]
Hi!

> Can I ask how exactly you are combining pytest-xdist with pytest-commander?

Just
pip install pytest-commander
pytest_commander /path/to/your/tests
no magic :)

pytest-xdist also installed, lines
```
[pytest]
addopts = -n auto --dist loadscope --showlocals --strict -l --tb=short
```
added to pytest.ini

> You can already run tests in multiple processes by clicking on multiple tests in the UI, each test or test group clicked will run in a separate process.

Usually, tests automatically starts from .bat/.sh file (not from GUI). xdist understands how to join test in scopes (some test can't be executed at same time). So, xdist suitable for routine checks.

pytest_commander considerd as GUI tool for manual start in cases of debug, or deep dive in particular problem, but it's not compabile with xdist.
Now, i use special decorator, to run particular test/tests during debug, and hoped to find more UX friendly way to do to it.

**Comment by ryanc414** [comment]
Ah cool, I hadn't considered the pytest.ini file. That actually provides quite a decent way to add plugins. However, as noted above it is expected that xdist will not work well when combined with pytest_commander. So ideally if there was some way to automatically deregister that plugin when running with pytest_commander but still allowing for it to be used when running directly via `pytest` that should solve the issue.

**Comment by v-polonskyi** [comment]
Tnx for support :)
