### ISSUE TITLE
Tests not executed

### ISSUE THREAD

**Issue by frankgerhardt** [ryanc414/pytest_runner#8]
![grafik](https://user-images.githubusercontent.com/550621/99002459-b7fcde00-253c-11eb-9b54-a4489436d97b.png)

I run a sample test from the pytest documentation from the web ui. All is good. Then I edit and save the file and in the console I see that the edited file is collected. But not executed. The message is "no tests ran".

I can execute the edited test with the play button in the web ui. My expectation is that the test does not only get collected but also executed. What's wrong here?

**Comment by ryanc414** [comment]
Hi, thanks for trying out the project. So tests should only be run when the play button is clicked from the UI. When a test file is modified, it is collected again to check for any changes - e.g. new test functions that can be displayed in the UI. Since this is only a collection, it is expected that the tests are not run. So it sounds like it is working as designed.

Maybe you are expecting a "watch" mode, similar to what Jest and other test runners have, where tests are automatically re-run as soon as there are changes detected? This is an interesting idea for unit-tests, though it might be problematic for more complex integration type tests which might take a long time to run.

**Comment by ryanc414** [comment]
I have implemented an "autorun" mode in https://github.com/ryanc414/pytest_commander/pull/9 - if you update to the latest v2.3.0 version you can try it like:

`$ pytest_commander path/to/your/tests -w autorun`

**Comment by frankgerhardt** [comment]
`-w autorun`  didn't work for me. I figured out the xdist and `--looponfail` serves me well. It seemed to me that pytest_commander would only log to the console but the UI would have to be updated manually.

**Comment by ryanc414** [comment]
Would you mind to give more details on why `-w autorun` didn't work? Did you definitely update to the latest version first (`pip install -U pytest_commander`)?
